project_id = "ibxnekfmezllousinvjc"

[functions.sitemap]
verify_jwt = false

[functions.seo-render]
verify_jwt = false

[functions.create-admin]
verify_jwt = false

[functions.drive-sync]
verify_jwt = false

[functions.video-proxy]
verify_jwt = false